version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  build:
    docker:
      - image: cimg/android:2023.10
    steps:
      - checkout
      - run:
            name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
            command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run: ./gradlew assemble
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-test-ci
