version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.10
    steps:
      - checkout
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run: ./gradlew assemble
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
#  notify:
#    docker:
#      - image: cimg/base:stable
#    steps:
#      - slack/notify:
#          custom: |
#            {
#              "blocks": [
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "plain_text",
#                      "text": "*This is a text notification*",
#                      "emoji": true
#                    }
#                  ]
#                }
#              ]
#            }
#          event: always
workflows:
  build-apk:
    jobs:
      - build:
          branches:
            - only: master